# Generated by Django 5.2.17 on 2026-09-16 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="班级 / 分组名称")),
                ("group_type", models.CharField(choices=[("HOMEROOM", "行政 / 班主任班级"), ("TEACHING", "教学分组")], default="HOMEROOM", max_length=16, verbose_name="分组类型")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_groups", to="schools.academicyear", verbose_name="学年")),
            ],
            options={
                "verbose_name": "班级 / 教学分组",
                "verbose_name_plural": "班级 / 教学分组",
                "ordering": ["academic_year__starts_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="HomeroomAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="关系本身有效")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("class_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="homeroom_assignments", to="academics.classgroup", verbose_name="班主任班级")),
                ("teacher_role", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="homeroom_assignments", to="accounts.roleassignment", verbose_name="教师角色授权")),
            ],
            options={
                "verbose_name": "班主任关系",
                "verbose_name_plural": "班主任关系",
            },
        ),
        migrations.CreateModel(
            name="StudentClassMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="关系本身有效")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("class_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="student_memberships", to="academics.classgroup", verbose_name="班级 / 教学分组")),
                ("student_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="class_memberships", to="students.studentschoolmembership", verbose_name="学生学校关系")),
            ],
            options={
                "verbose_name": "学生班级关系",
                "verbose_name_plural": "学生班级关系",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, verbose_name="学科代码")),
                ("name", models.CharField(max_length=120, verbose_name="学科名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_records", to="schools.school")),
            ],
            options={
                "verbose_name": "学科",
                "verbose_name_plural": "学科",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="关系本身有效")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("class_group", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="academics.classgroup", verbose_name="班级 / 教学分组")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="academics.subject", verbose_name="学科")),
                ("teacher_role", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="teaching_assignments", to="accounts.roleassignment", verbose_name="教师角色授权")),
            ],
            options={
                "verbose_name": "任课关系",
                "verbose_name_plural": "任课关系",
            },
        ),
        migrations.AddConstraint(
            model_name="classgroup",
            constraint=models.UniqueConstraint(fields=("academic_year", "name"), name="uniq_class_group_name_per_academic_year"),
        ),
        migrations.AddConstraint(
            model_name="homeroomassignment",
            constraint=models.UniqueConstraint(fields=("teacher_role", "class_group"), name="uniq_homeroom_assignment"),
        ),
        migrations.AddConstraint(
            model_name="studentclassmembership",
            constraint=models.UniqueConstraint(fields=("student_membership", "class_group"), name="uniq_student_class_membership"),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(fields=("school", "code"), name="uniq_subject_code_per_school"),
        ),
        migrations.AddConstraint(
            model_name="teachingassignment",
            constraint=models.UniqueConstraint(fields=("teacher_role", "class_group", "subject"), name="uniq_teaching_assignment"),
        ),
    ]
