# Generated by Django 5.2.17 on 2026-09-16 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=150, verbose_name="学生姓名")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("user_account", models.OneToOneField(blank=True, help_text="学生可以暂时没有登录账号；账号与学生业务身份保持分离。", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="student_identity", to=settings.AUTH_USER_MODEL, verbose_name="学生登录账号")),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentSchoolMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_number", models.CharField(help_text="该学生在本校内稳定使用的学号；同一学校内唯一。", max_length=64, verbose_name="学校学号")),
                ("status", models.CharField(choices=[("ACTIVE", "在读"), ("SUSPENDED", "暂停"), ("WITHDRAWN", "已离校"), ("ALUMNI", "校友")], default="ACTIVE", max_length=16, verbose_name="状态")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="%(app_label)s_%(class)s_records", to="schools.school")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="school_memberships", to="students.student", verbose_name="学生")),
            ],
            options={
                "verbose_name": "学生学校关系",
                "verbose_name_plural": "学生学校关系",
            },
        ),
        migrations.CreateModel(
            name="GuardianRelationship",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relationship_type", models.CharField(choices=[("PARENT", "家长"), ("LEGAL_GUARDIAN", "法定监护人"), ("OTHER_AUTHORISED", "其他授权监护人")], default="PARENT", max_length=24, verbose_name="关系类型")),
                ("is_active", models.BooleanField(default=True, verbose_name="有效")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("guardian", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="guardian_relationships", to=settings.AUTH_USER_MODEL, verbose_name="家长 / 监护人账号")),
                ("student_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="guardian_relationships", to="students.studentschoolmembership", verbose_name="学生学校关系")),
            ],
            options={
                "verbose_name": "家长学生关系",
                "verbose_name_plural": "家长学生关系",
            },
        ),
        migrations.AddConstraint(
            model_name="studentschoolmembership",
            constraint=models.UniqueConstraint(fields=("school", "student"), name="uniq_student_membership_per_school"),
        ),
        migrations.AddConstraint(
            model_name="studentschoolmembership",
            constraint=models.UniqueConstraint(fields=("school", "student_number"), name="uniq_student_number_per_school"),
        ),
        migrations.AddConstraint(
            model_name="guardianrelationship",
            constraint=models.UniqueConstraint(fields=("student_membership", "guardian"), name="uniq_guardian_per_student_membership"),
        ),
    ]
