# Generated by Django 5.2.17 on 2026-09-16 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCycle",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="报告周期名称")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("academic_year", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_cycles", to="schools.academicyear", verbose_name="学年")),
            ],
            options={
                "verbose_name": "报告周期",
                "verbose_name_plural": "报告周期",
                "ordering": ["academic_year__starts_on", "name"],
            },
        ),
        migrations.CreateModel(
            name="StudentReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("DRAFT", "填写中"), ("IN_REVIEW", "待班主任审核"), ("RETURNED", "已退回修改"), ("APPROVED", "已批准"), ("PUBLISHED", "已发布")], default="DRAFT", max_length=16, verbose_name="状态")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="发布时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="published_student_reports", to=settings.AUTH_USER_MODEL, verbose_name="发布人")),
                ("report_cycle", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="student_reports", to="reports.reportcycle", verbose_name="报告周期")),
                ("student_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reports", to="students.studentschoolmembership", verbose_name="学生学校关系")),
            ],
            options={
                "verbose_name": "学生报告",
                "verbose_name_plural": "学生报告",
            },
        ),
        migrations.CreateModel(
            name="SubjectComment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("student_feedback", models.TextField(blank=True, verbose_name="学生可见反馈")),
                ("guardian_message", models.TextField(blank=True, verbose_name="家长专属信息")),
                ("staff_note", models.TextField(blank=True, verbose_name="教职工内部备注")),
                ("status", models.CharField(choices=[("DRAFT", "草稿"), ("SUBMITTED", "已提交"), ("RETURNED", "已退回")], default="DRAFT", max_length=16, verbose_name="状态")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="最近提交时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_subject_comments", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subject_comments", to="reports.studentreport", verbose_name="学生报告")),
                ("subject", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_comments", to="academics.subject", verbose_name="学科")),
                ("submitted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="submitted_subject_comments", to=settings.AUTH_USER_MODEL, verbose_name="最近提交人")),
            ],
            options={
                "verbose_name": "学科评价",
                "verbose_name_plural": "学科评价",
                "ordering": ["subject__code"],
            },
        ),
        migrations.CreateModel(
            name="ReportAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("action", models.CharField(choices=[("RETURN_SUBJECT", "退回学科评价"), ("APPROVE", "批准报告"), ("PUBLISH", "发布报告")], max_length=24, verbose_name="动作")),
                ("note", models.TextField(blank=True, verbose_name="说明")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="report_actions", to=settings.AUTH_USER_MODEL, verbose_name="操作人")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="actions", to="reports.studentreport", verbose_name="学生报告")),
                ("subject_comment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="review_actions", to="reports.subjectcomment", verbose_name="目标学科评价")),
            ],
            options={
                "verbose_name": "报告工作流动作",
                "verbose_name_plural": "报告工作流动作",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="reportcycle",
            constraint=models.UniqueConstraint(fields=("academic_year", "name"), name="uniq_report_cycle_name_per_year"),
        ),
        migrations.AddConstraint(
            model_name="studentreport",
            constraint=models.UniqueConstraint(fields=("report_cycle", "student_membership"), name="uniq_student_report_per_cycle"),
        ),
        migrations.AddConstraint(
            model_name="subjectcomment",
            constraint=models.UniqueConstraint(fields=("report", "subject"), name="uniq_subject_comment_per_report"),
        ),
    ]
